- name: Docker-dokumentation
  href: index.md
- name: Snabbstart
  expanded: true
  items:
    - name: Docker Marketplace-mall
      href: 'https://azuremarketplace.microsoft.com/en-us/marketplace/apps/CanonicalandMSOpenTech.DockerOnUbuntuServer1404LTS'
- name: Självstudier
  items:
    - name: Python-webbapp med Docker och PostgreSQL
      href: ../app-service/containers/tutorial-python-postgresql-app.md?toc=%2fazure%2fpostgresql%2ftoc.json
    - name: CI/CD med Docker Swarm och Azure DevOps
      href: /azure/container-service/container-service-docker-swarm-mode-setup-ci-cd-acs-engine
    - name: 'CI/CD med Docker, Jenkins och Linux'
      href: /azure/virtual-machines/linux/tutorial-jenkins-github-docker-cicd
- name: Instruktionsguider
  items:
    - name: Docker VM-tillägg
      href: /azure/virtual-machines/linux/dockerextension
    - name: Docker-dator
      href: /azure/virtual-machines/linux/docker-machine
    - name: Docker-containerregister
      href: /azure/container-registry/container-registry-get-started-portal
- name: Resurser
  items:
    - name: Azure-översikt
      href: 'https://azure.microsoft.com/roadmap/'
    - name: Docker Azure-drivrutin
      href: 'https://docs.docker.com/machine/drivers/azure/'
    - name: Docker Azure-webbplats
      href: 'https://www.docker.com/docker-azure'
    - name: Docker-webbplats
      href: 'https://docker.com'