- name: Dokumentation om Ansible på Azure
  href: ./index.yml
- name: Översikt
  items:
    - name: Om Ansible på Azure
      href: ./ansible-overview.md
- name: Snabbstarter
  expanded: true
  items:
    - name: Distribuera Ansible-lösningsmallar till CentOS
      href: ./ansible-deploy-solution-template.md
    - name: Installera Ansible på virtuella Linux-datorer
      href: /azure/virtual-machines/linux/ansible-install-configure
      maintainContext: true
    - name: Köra spelböcker i Cloud Shell
      href: ./ansible-run-playbook-in-cloudshell.md
    - name: Arbeta med virtuella Linux-datorer
      expanded: true
      items:
        - name: Konfigurera virtuella Linux-datorer
          href: /azure/virtual-machines/linux/ansible-create-vm
          maintainContext: true
        - name: Hantera virtuella Linux-datorer
          href: /azure/virtual-machines/linux/ansible-manage-linux-vm
          maintainContext: true
- name: Självstudier
  items:
    - name: Azure Application Gateway
      items:
        - name: Hantera webbtrafik
          href: ./ansible-create-configure-application-gateway.md
    - name: Azure App Service
      items:
        - name: Konfigurera appar
          href: ./ansible-create-configure-azure-web-apps.md
        - name: Skala appar
          href: ./ansible-scale-azure-web-apps.md
    - name: Azure DevTest Labs
      items:
        - name: Konfigurera labb
          href: ./ansible-devtest-labs-configure.md
    - name: Azure Kubernetes Service (AKS)
      items:
        - name: Konfigurera AKS-kluster
          href: ./ansible-create-configure-aks.md
        - name: Konfigurera Azure CNI-nätverk
          href: ./ansible-aks-configure-cni-networking.md
        - name: Konfigurera kubenet-nätverk
          href: ./ansible-aks-configure-kubenet-networking.md
        - name: Konfigurera RBAC-roller i AKS-kluster
          href: ./ansible-aks-configure-rbac.md
    - name: Azure HDInsight
      items:
        - name: Konfigurera kluster
          href: ./ansible-azure-hdinsight-configure.md
    - name: Azure Service Bus
      items:
        - name: Konfigurera köer
          href: ./ansible-service-bus-queue-configure.md
        - name: Konfigurera ämnen
          href: ./ansible-service-bus-topic-configure.md
    - name: Databas
      items:
        - name: Konfigurera Azure Database for MySQL
          href: ./ansible-create-configure-mysql.md
        - name: Konfigurera Azure Cosmos DB-konton
          href: ./ansible-data-cosmos-configure.md
        - name: Konfigurera Azure Cache for Redis
          href: ./ansible-data-cache-for-redis-configure.md
    - name: Dynamiskt lager
      items:
        - name: Hantera dina Azure-resurser
          href: ./ansible-manage-azure-dynamic-inventories.md
    - name: Skalningsuppsättningar för virtuella datorer
      items:
        - name: Konfigurera
          href: ./ansible-create-configure-vmss.md
        - name: Distribuera
          href: ./ansible-deploy-app-vmss.md
        - name: Automatisk skalning
          href: ./ansible-auto-scale-vmss.md
        - name: Uppdatera anpassade avbildningar
          href: ./ansible-vmss-update-image.md
    - name: Virtuellt nätverk
      items:
        - name: Konfigurera peering
          href: ./ansible-vnet-peering-configure.md
        - name: Konfigurera routningstabeller
          href: ./ansible-create-configure-route-table.md
- name: Exempel
  items:
    - name: Ansible-labbuppgifter för Azure
      href: 'https://github.com/microsoft/ansiblelabs'
    - name: Exempel på Ansible Azure-spelböcker
      href: 'https://github.com/Azure-Samples/ansible-playbooks'
- name: Referens
  items:
    - name: Spelboksroller
      items:
        - name: azure_module
          href: 'https://galaxy.ansible.com/Azure/azure_modules/'
        - name: azure_preview_module
          href: 'https://galaxy.ansible.com/Azure/azure_preview_modules'
    - name: Versioner och funktioner
      href: ./ansible-matrix.md
    - name: Alla moduler för Azure
      href: 'https://docs.ansible.com/ansible/latest/modules/list_of_cloud_modules#azure'
- name: Verktyg
  items:
    - name: Visual Studio Code-tillägg för Ansible
      href: 'https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible'