items:
- name: Dokumentation om Ansible på Azure
  href: ./index.yml
- name: Översikt
  items:
  - name: Om Ansible på Azure
    href: ./ansible-overview.md
- name: Snabbstarter
  items:
  - name: Installera Ansible på en virtuell Linux-dator
    href: /azure/virtual-machines/linux/ansible-install-configure
    maintainContext: true
  - name: Skapa en virtuell Linux-dator
    href: /azure/virtual-machines/linux/ansible-create-vm
    maintainContext: true
  - name: Hantera en virtuell Linux-dator
    href: /azure/virtual-machines/linux/ansible-manage-linux-vm
    maintainContext: true
  expanded: true
- name: Självstudier
  items:
  - name: Kör en spelbok i Cloud Shell
    href: ./ansible-run-playbook-in-cloudshell.md
    maintainContext: true
  - name: Hantera dynamiska lager
    href: ./ansible-manage-azure-dynamic-inventories.md
    maintainContext: true
  - name: Skapa och konfigurera VMSS
    href: ./ansible-create-configure-vmss.md
  - name: Distribuera app till VMSS
    href: ./ansible-deploy-app-vmss.md
  - name: Skapa och konfigurera AKS-kluster
    href: ./ansible-create-configure-aks.md
  - name: Skapa och konfigurera Azure Application Gateway
    href: ./ansible-create-configure-application-gateway.md
  - name: Skapa och konfigurera Azure DB för MySQL
    href: ./ansible-create-configure-mysql.md
  - name: Skapa och konfigurera Azure Web Apps
    href: ./ansible-create-configure-azure-web-apps.md
- name: Referens
  items:
  - name: Spelboksroller
    items:
    - name: azure_module
      href: https://galaxy.ansible.com/Azure/azure_modules/
    - name: azure_preview_module
      href: https://galaxy.ansible.com/Azure/azure_preview_modules
  - name: Versioner och funktioner
    href: ./ansible-matrix.md
  - name: Azure Container Instances
    href: https://docs.ansible.com/ansible/latest/azure_rm_containerinstance_module.html
  - name: Azure Functions
    href: https://docs.ansible.com/ansible/latest/azure_rm_functionapp_module.html
  - name: Lastbalanserare
    href: https://docs.ansible.com/ansible/latest/azure_rm_loadbalancer_module.html
  - name: Virtuella datorer
    href: https://docs.ansible.com/ansible/latest/azure_rm_virtualmachine_module.html
  - name: Alla moduler för Azure
    href: https://docs.ansible.com/ansible/latest/list_of_cloud_modules.html#azure
- name: Verktyg
  items:
  - name: Visual Studio Code-tillägg för Ansible
    href: https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible
ms.openlocfilehash: 4190429ddd0189c937577257f07a21fcf6687ad2
ms.sourcegitcommit: 5d837a7557363424e0183d5f04dcb23a8ff966bb
ms.translationtype: HT
ms.contentlocale: sv-SE
ms.lasthandoff: 12/06/2018
ms.locfileid: "52966542"
