- name: Kubernetes på Azure
  href: ./index.yml
- name: Översikt
- name: Snabbstarter
  expanded: true
- name: Självstudier
- name: Begrepp
- name: Anvisningar
  items:
    - name: Spara data med Azure Files
      href: ../../aks/azure-files.md?toc=%2fazure%2fcontainer-service%2fkubernetes%2ftoc.json
    - name: Övervaka
    - name: Distribuera Spring Boot-appar
      items:
        - name: Distribuera ett Spring Boot-program på Linux i Azure Container Service
          href: container-service-deploy-spring-boot-app-on-linux.md
        - name: Distribuera ett Spring Boot-program på ett Kubernetes-kluster i Azure Container Service
          href: container-service-deploy-spring-boot-app-on-kubernetes.md
        - name: Distribuera en Spring Boot-app med fabric8 Maven-pluginprogrammet
          href: container-service-deploy-spring-boot-app-using-fabric8-maven-plugin.md
- name: Referens
  items:
    - name: Azure CLI
      href: /cli/azure/acs
    - name: PowerShell
      href: /powershell/module/az.compute
    - name: REST
      href: /rest/api/container-service
- name: Resurser
  items:
    - name: Azure-översikt
      href: 'https://azure.microsoft.com/roadmap/'
    - name: Mallar – ACS-motor
      href: 'https://github.com/Azure/acs-engine'
    - name: Prissättning
      href: 'https://azure.microsoft.com/pricing/details/container-service/'
    - name: Regional tillgänglighet
      href: 'https://azure.microsoft.com/regions/services/'
    - name: Stack Overflow
      href: 'https://stackoverflow.com/questions/tagged/azure-container-service'
    - name: Videoklipp
      href: 'https://azure.microsoft.com/resources/videos/index/?services=container-service&sort=newest'